### ISSUE TITLE
Revisar Feature Envy en COOPWindow>>ignoreRule

### ISSUE THREAD

**Issue by fdodino** [MartinEGonzalez95/COOP#12]
Hay 5 mensajes enviados a `RuleList`, se puede directamente enviar el mensaje `ignore` y que devuelva un `true/false` para que muestre/no muestre popup o bien haga un inform. La vista únicamente se encarga del popup/inform y el RuleList sabe cuál es la regla seleccionada y se encarga de disparar la notificación a los interesados mediante el `changed: #rules`, _à la Arena_.

**Comment by MartinEGonzalez95** [comment]
Solucionado en https://github.com/MartinEGonzalez95/COOP/pull/14

**Comment by fdodino** [comment]
Los issues que abro los cierro yo, muchachios, como dice la guía. Lo reabro para mirarlo depois.

**Comment by MartinEGonzalez95** [comment]
> Los issues que abro los cierro yo, muchachios, como dice la guía. Lo reabro para mirarlo depois.

Upps Perdon!!
